allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  less: set this to true or false
  lmdb: false
  msgpackr-extract: false
  nx: true
  protobufjs: false
  unrs-resolver: false
