load("//tools:defaults.bzl", "ts_library")

ts_library(
    name = "store",
    srcs = glob([
        "*.ts",
        "src/**/*.ts",
    ]),
    module_name = "@ngrx/store",
    visibility = ["//visibility:public"],
    deps = ["@rxjs"],
)
