name: Documentation Report
description: Report missing or inaccurate documentation
labels: ['Comp: Docs']

body:
  - type: markdown
    attributes:
      value: |
        ❤️ ngrx? Please consider supporting our collective: 👉  [donate](https://opencollective.com/ngrx/donate)
        Please search GitHub for a similar issue or PR before submitting a new issue

  - type: textarea
    id: information
    attributes:
      label: Information
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Documentation page
      description: Add the documentation URL

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: Yes
        - label: No
