/**
 * DO NOT EDIT
 *
 * This file is automatically generated (as a pre-commit step)
 */

export = {
  parser: '@typescript-eslint/parser',

  plugins: ['@ngrx'],
  rules: { '@ngrx/updater-explicit-return-type': 'error' },
};
