import { InjectionToken } from '@angular/core';
export declare const _INITIAL_STATE: InjectionToken<{}>;
export declare const INITIAL_STATE: InjectionToken<{}>;
export declare const REDUCER_FACTORY: InjectionToken<{}>;
export declare const _REDUCER_FACTORY: InjectionToken<{}>;
export declare const INITIAL_REDUCERS: InjectionToken<{}>;
export declare const _INITIAL_REDUCERS: InjectionToken<{}>;
export declare const META_REDUCERS: InjectionToken<{}>;
export declare const STORE_FEATURES: InjectionToken<{}>;
export declare const _STORE_REDUCERS: InjectionToken<{}>;
export declare const _FEATURE_REDUCERS: InjectionToken<{}>;
export declare const _FEATURE_REDUCERS_TOKEN: InjectionToken<{}>;
export declare const FEATURE_REDUCERS: InjectionToken<{}>;
