name: Collect Docs

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  collect-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm install --global corepack@0.31.0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm exec nx run-many -t build --exclude=www --skip-nx-cache --parallel=3
      - run: pnpm exec nx run www:collect-docs --skip-nx-cache
      - name: Create pull request for updated API reference docs
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            projects/www/src/app/reference/
          commit-message: docs: update API reference [skip ci]
          branch: chore/update-api-reference-docs
          title: 'docs: update API reference'
          body: |
            This PR was automatically generated by the collect-docs workflow.

            It updates API reference JSON files under `projects/www/src/app/reference/`.
