# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# The used configurations are set up in .github/labeler.yml
# For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
